version: "3.2"
services:
  web:
    build: .
    ports:
      - "6000:6000"
    volumes:
      - type: volume
        source: tetrisdata
        target: /tetris/data
        volume:
          nocopy: true
    logging:
      driver: journald
      options:
        tag: tetrislog
    restart: always
    # networks:
    #   - webnet
# networks:
#   webnet:
volumes:
  tetrisdata:
